name: Post to Facebook Page

on:
  push:
    paths:
      - 'articles/**'  # 當 articles 資料夾有變更時觸發
  workflow_dispatch:   # 允許手動觸發

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read article content
        id: article
        run: |
          # 找出 articles 目錄下最新修改的 .md 檔案
          LATEST_ARTICLE=$(find articles -name "*.md" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
          # 讀取文章內容
          CONTENT=$(cat "$LATEST_ARTICLE")
          # 將內容轉換為可在 GitHub Actions 中傳遞的格式
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

      - name: Post to Facebook
        id: fb_post
        run: |
          # 發布文章 - 使用簡化的 API 呼叫
          echo "正在發布文章到 Facebook..."
          POST_RESPONSE=$(curl -s -X POST \
            "https://graph.facebook.com/v22.0/${{ secrets.FB_PAGE_ID }}/feed" \
            -F "message=${{ steps.article.outputs.content }}" \
            -F "access_token=${{ secrets.FB_ACCESS_TOKEN }}")

          if echo "$POST_RESPONSE" | grep -q "error"; then
            echo "發布失敗:"
            echo "$POST_RESPONSE"
            exit 1
          fi

          POST_ID=$(echo "$POST_RESPONSE" | jq -r '.id')
          echo "發布成功！文章 ID: $POST_ID"
          echo "post_id=$POST_ID" >> $GITHUB_OUTPUT

      - name: Handle errors
        if: failure()
        run: |
          echo "工作流程失敗。請確認以下事項："
          echo "1. FB_PAGE_ID 是否正確設定"
          echo "2. FB_ACCESS_TOKEN 是否具有足夠權限 (需要 pages_read_engagement 和 pages_manage_posts)"
          echo "3. Access Token 是否過期"