name: Post to Facebook Page

on:
  push:
    paths:
      - 'articles/**'  # 當 articles 資料夾有變更時觸發
  workflow_dispatch:   # 允許手動觸發

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read article content
        id: article
        run: |
          # 找出 articles 目錄下最新修改的 .md 檔案
          LATEST_ARTICLE=$(find articles -name "*.md" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
          # 讀取文章內容
          CONTENT=$(cat "$LATEST_ARTICLE")
          # 將內容轉換為可在 GitHub Actions 中傳遞的格式
          CONTENT="${CONTENT//'%'/'%25'}"
          CONTENT="${CONTENT//$'\n'/'%0A'}"
          CONTENT="${CONTENT//$'\r'/'%0D'}"
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

      - name: Post to Facebook
        run: |
          curl -X POST \
            "https://graph.facebook.com/v16.0/${{ secrets.FB_PAGE_ID }}/feed" \
            -d "message=${{ steps.article.outputs.content }}" \
            -d "access_token=${{ secrets.FB_ACCESS_TOKEN }}"